# Generated by Django 4.2.7 on 2026-04-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Numéro')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacité')),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=10)),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Table',
                'ordering': ['number'],
            },
        ),
    ]
