# Generated by Django 4.2.7 on 2026-04-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone')),
                ('description', models.TextField(blank=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Frais de livraison')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'ordering': ['name'],
            },
        ),
    ]
